sync upstream cleanup and refactoring

diff --git a/thirdparty/foamx3m/wmake/wmake b/thirdparty/foamx3m/wmake/wmake
--- a/thirdparty/foamx3m/wmake/wmake
+++ b/thirdparty/foamx3m/wmake/wmake
@@ -2,9 +2,9 @@
 #------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | foam-extend: Open Source CFD
-#  \\    /   O peration     |
-#   \\  /    A nd           | For copyright notice see file Copyright
-#    \\/     M anipulation  |
+#  \\    /   O peration     | Version:     4.1
+#   \\  /    A nd           | Web:         http://www.foam-extend.org
+#    \\/     M anipulation  | For copyright notice see file Copyright
 #------------------------------------------------------------------------------
 # License
 #     This file is part of foam-extend.
@@ -34,8 +34,15 @@ Script=${0##*/}
 usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-usage: $Script [dir]
-       $Script target [dir [MakeDir]]
+
+Usage: $Script [OPTION] [dir]
+       $Script [OPTION] target [dir [MakeDir]]
+
+options:
+  -s | -silent      Run make in 'silent' mode (do not echo commands)
+  -a | -all         Run wmake in all subdirectories
+  -h | -help        Print the usage
+
 
 A general, easy-to-use make system for multi-platform development
 
@@ -54,28 +61,62 @@ USAGE
     exit 1
 }
 
-# provide immediate help, even if none of the environment is set
-if [ "$1" = "-h" -o "$1" = "-help" ]
-then
-    usage
-fi
+
+# Default make is the "make" in the path
+make="make"
 
 
-# check environment variables
-for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+#------------------------------------------------------------------------------
+# Parse arguments and options
+#------------------------------------------------------------------------------
+
+# Default to compiling the local target only
+all=
+
+while [ "$#" -gt 0 ]
 do
-    eval test "\$$check" || {
-        echo "$Script error: environment variable \$$check not set" 1>&2
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -s | -silent)
+        make="$make -s"
+        shift
+        ;;
+    -a | -all | all)
+        all="all"
+        shift
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
+
+
+#------------------------------------------------------------------------------
+# Check environment variables
+#------------------------------------------------------------------------------
+
+for envar in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+do
+    eval test "\$$envar" || {
+        echo "$Script error: environment variable \$$envar not set" 1>&2
         exit 1
     }
 done
 
-# when compiling anything but a standalone exe:
-# WM_PROJECT and WM_PROJECT_DIR must be set
+
+# When compiling anything but a standalone exe WM_PROJECT and WM_PROJECT_DIR
+# must be set
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
     echo "$Script error:" 1>&2
-    echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set" 1>&2
-    echo  "   while building project library" 1>&2
+    echo "    environment variable \$WM_PROJECT or " \
+         "\$WM_PROJECT_DIR not set" 1>&2
+    echo "    while building project library" 1>&2
     exit 1
 }
 
@@ -87,17 +128,20 @@ done
 make="make"
 
 # set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
-if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]; then
+if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]
+then
     WM_NCOMPPROCS=$(wmakeScheduler -count)
     [ $? -eq 0 ] || unset WM_NCOMPPROCS
 fi
 
-if [ "$WM_NCOMPPROCS" ]; then
-    if [ "$WM_NCOMPPROCS" -gt 1  ]; then  # -a ! "$MAKEFLAGS" # not having -a ! "$MAKEFLAGS" leads to make warning
-   
+if [ "$WM_NCOMPPROCS" ]
+then
+    if [ "$WM_NCOMPPROCS" -gt 1 -a ! "$MAKEFLAGS" ]
+    then
         lockDir=$HOME/.wmakeScheduler
 
-        if [ -d $lockDir ]; then
+        if [ -d $lockDir ]
+        then
             rm -f $lockDir/*
         else
             mkdir -p $lockDir
@@ -117,22 +161,26 @@ MakeDir=Make
 
 if [ $# -ge 1 ]
 then
-    if [ -d "$1" ]; then
+    if [ -d "$1" ]
+    then
         dir=$1
     else
         makeOption=$1
     fi
 
-    if [ $# -ge 2 ]; then
+    if [ $# -ge 2 ]
+    then
         dir=$2
     fi
 
     # alternative name for the Make sub-directory
-    if [ $# -ge 3 ];  then
+    if [ $# -ge 3 ]
+    then
         MakeDir=$3
     fi
 
-    if [ "$dir" ]; then
+    if [ "$dir" ]
+    then
         cd $dir 2>/dev/null || {
             echo "$Script error: could not change to directory '$dir'" 1>&2
             exit 1
@@ -145,22 +193,20 @@ fi
 # Recurse the application directories tree
 #------------------------------------------------------------------------------
 
-if [ "$makeOption" = all ]
+if [ "$all" = all ]
 then
-    if [ -e Allwmake ];  then
+    if [ -e Allwmake ]
+    then
         ./Allwmake
         exit $?
-    elif [ ! -d $MakeDir ]; then
+    elif [ ! -d $MakeDir ]
+    then
         # FOAM_APPS=$(find . -maxdepth 1 \( -type d -a ! -name "." -a ! -name Optional -a ! -name Make \)  -printf "%f ")
         # avoid 'find' with '-printf' ... not entirely portable
         FOAM_APPS=$(for d in *; do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] && echo "$d"; done | xargs)
         $make -k -f $WM_DIR/MakefileApps FOAM_APPS="$FOAM_APPS"
         exit $?
     fi
-
-    # This is the end of the recursion down the application directories tree
-    # so remove the "all" option so that the call to make builds the application
-    makeOption=
 fi
 
 
@@ -217,7 +263,8 @@ esac
 $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps $OBJECTS_DIR/dependencies
 
 retVal=$?
-if [ $retVal -ne 0 ]; then
+if [ $retVal -ne 0 ]
+then
     exit $retVal
 fi
 
